-include config.mk

DEPS=GNUMakefile

ifdef HAVE_CONFIG_MK
DEPS += config.mk
endif

WCC_INCS=-I$(WATCOM)\h\win
WCC_CFLAGS=-q -wx -s -zls -6s -fp6 -mf -DVXD32 -fpi87 -ei -oeatxhn
WCC_AFLAGS=-q
WCC_CC=wcc386
WCC_AS=wasm
FASM=fasm
BIN2H=bin2h

GCC_CC=gcc
GCC_INC=-I.
GCC_CFLAGS=-std=c99 -Wall -DSMP9X
GCC_LDFLAGS=
GCC_LDFLAGS_WIN=-mwindows $(GCC_LDFLAGS)

BIN=smp.vxd
TOOLS=fixlink.exe
SMP_VXD_OBJS=smp.wcc.obj vxd_lib.wcc.obj vxd_debug.wcc.obj smp_init.wcc.obj smp_proc.wcc.obj \
  vxd_terror.wcc.obj taskswitch.wcc.obj paging.wcc.obj

SMP_LIB_OBJS=smp9x.gcc.o
SMP_TESTS=tests/prime.exe tests/smpload.exe tests/systemcall.exe
SMP_TESTS_OBJS=tests/smpload.gcc.o tests/prime.gcc.o tests/systemcall.gcc.o

ifdef DEBUG
  WCC_CFLAGS += -DDEBUG
endif

ifdef APP_DEBUG
  GCC_CFLAGS += -O1 -g
else
  GCC_CFLAGS += -O2
endif

all: $(BIN)
tests: all $(SMP_TESTS)
.PHONY: all tests clean

smp_init.wcc.obj: apboot.h apkernel.h

%.wcc.obj: %.c $(DEPS)
	$(WCC_CC) -fo=$@ $(WCC_CFLAGS) $(WCC_INCS) $<

#%.obj: %.asm $(DEPS)
#	$(WCC_AS) $(AFLAGS) $<

%.fasm.obj: %.asm $(DEPS)
	$(FASM) $< $@

%.gcc.o: %.c $(GCC_DEPS)
	$(GCC_CC) $(GCC_CFLAGS) $(GCC_INC) -c -o $@ $<

apboot.h: apboot.asm
	$(FASM) apboot.asm apboot.bin
	bin2h apboot.bin apboot.h -id=apboot

apkernel.h: apkernel.asm
	$(FASM) apkernel.asm apkernel.bin
	bin2h apkernel.bin apkernel.h -id=apkernel

fixlink.exe : fixlink\fixlink.c
	wcl386 -q $< -fe=$@

tests/smpload.exe: tests/smpload.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS_WIN)

tests/prime.exe: $(SMP_LIB_OBJS) tests/prime.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS)

tests/systemcall.exe: $(SMP_LIB_OBJS) tests/systemcall.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS)

%.lnk: GNUMakefile
	echo system win_vxd dynamic > $@
	echo option map=$*.map >> $@
	echo option nodefaultlibs >> $@
	echo name $(BIN) >> $@
	$(foreach obj,$(SMP_VXD_OBJS),echo file $(obj) >> $@ &&) true
	echo segment '_TEXT'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment '_DATA'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment 'CONST'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment 'CONST2' PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment '_BSS'   PRELOAD NONDISCARDABLE IOPL >> $@
	echo export VXD_DDB.1 >> $@

$(BIN): $(TOOLS) $(SMP_VXD_OBJS) smp.lnk
	wlink op quiet @smp.lnk
	fixlink.exe -vxd32 $@

clean:
	-$(RM) smp.lnk
	-$(RM) *.err
	-$(RM) $(SMP_VXD_OBJS)
	-$(RM) $(BIN)
	-$(RM) $(SMP_LIB_OBJS)
	-$(RM) $(SMP_TESTS)
	-$(RM) $(SMP_TESTS_OBJS)
