-include config.mk

DEPS=GNUMakefile

ifdef HAVE_CONFIG_MK
DEPS += config.mk
endif

WCC_INCS=-I$(WATCOM)\h\win
WCC_CFLAGS=-q -wx -s -zls -6s -fp6 -mf -DVXD32 -fpi87 -ei -oeatxhn
WCC_AFLAGS=-q
WCC_CC=wcc386
WCC_AS=wasm
FASM=fasm
BIN2H=bin2h
CAT=cat
CP=cp -f

GCC_CC=gcc
GCC_INC=-I.
GCC_CFLAGS=-std=c99 -Wall -DSMP9X -DNOCRT -DNOCRT_FLOAT -DNOCRT_NOREPLACE
GCC_LDFLAGS=
GCC_LDFLAGS_WIN=-mwindows $(GCC_LDFLAGS)

BIN=smp.vxd
TOOLS=fixlink.exe generator.exe

SMP_VXD_OBJS=smp.wcc.obj vxd_lib.wcc.obj vxd_debug.wcc.obj smp_init.wcc.obj smp_proc.wcc.obj \
  vxd_terror.wcc.obj taskswitch.wcc.obj paging.wcc.obj

SMP9X_OBJS=smp9x.gcc.o

NOCRT_OBJS=nocrt/nocrt.gcc.o nocrt/nocrt_math.gcc.o

LIBSMP_OBJS=$(SMP9X_OBJS) libsmp_hook.o libsmp/libsmp.gcc.o libsmp/tryentercriticalsection.gcc.o
MESASMP_OBJS=$(SMP9X_OBJS) $(NOCRT_OBJS) libsmp/copy.fasm.o mesa_hook.o libsmp/libsmp.gcc.o libsmp/tryentercriticalsection.gcc.o

SMP_TESTS=tests/prime1.exe tests/prime2.exe tests/prime3.exe tests/smpload.exe tests/systemcall.exe \
  tests/doscall.exe

SMP_TESTS_OBJS=tests/smpload.gcc.o tests/prime1.gcc.o tests/prime2.gcc.o tests/prime3.gcc.o \
  tests/systemcall.gcc.o tests/doscall.gcc.o

GENERATED=libsmp.def libsmp.txt mesasmp.txt mesasmp.def mesa_hook.asm libsmp_hook.asm apboot.bin apboot.h apkernel.bin apkernel.h

ifdef DEBUG
  WCC_CFLAGS += -DDEBUG
endif

ifdef APP_DEBUG
  GCC_CFLAGS += -O1 -g
else
  GCC_CFLAGS += -O2
endif

all: $(BIN) libsmp.dll mesasmp.dll tests
tests: $(SMP_TESTS)
.PHONY: all tests clean

smp_init.wcc.obj: apboot.h apkernel.h

%.wcc.obj: %.c $(DEPS)
	$(WCC_CC) -fo=$@ $(WCC_CFLAGS) $(WCC_INCS) $<

#%.obj: %.asm $(DEPS)
#	$(WCC_AS) $(AFLAGS) $<

%.fasm.o: %.asm $(DEPS)
	$(FASM) $< $@

%.gcc.o: %.c $(GCC_DEPS)
	$(GCC_CC) $(GCC_CFLAGS) $(GCC_INC) -c -o $@ $<

apboot.h: apboot.asm
	$(FASM) apboot.asm apboot.bin
	bin2h apboot.bin apboot.h -id=apboot

apkernel.h: apkernel.asm
	$(FASM) apkernel.asm apkernel.bin
	bin2h apkernel.bin apkernel.h -id=apkernel

fixlink.exe: fixlink\fixlink.c
	wcl386 -q $< -fe=$@
	
generator.exe: libsmp\generator.c
	gcc -std=c99 -Wall libsmp\generator.c -o $@

libsmp.txt: libsmp\kernel32.txt libsmp\msvcrt.txt
	$(CAT) libsmp\kernel32.txt > $@
	$(CAT) libsmp\msvcrt.txt >> $@

libsmp_hook.o: generator.exe libsmp.txt
	generator libsmp.txt libsmp_hook.asm libsmp.def
	$(CAT) libsmp/smp9x.def >> libsmp.def
	$(FASM) libsmp_hook.asm $@

mesasmp.txt: libsmp\kernel32.txt libsmp\msvcrt_nocrt.txt libsmp\ws2_32.txt
	$(CAT) libsmp\kernel32.txt > $@
	$(CAT) libsmp\msvcrt_nocrt.txt >> $@
	$(CAT) libsmp\ws2_32.txt >> $@

mesa_hook.o: generator.exe mesasmp.txt
	generator mesasmp.txt mesa_hook.asm mesasmp.def
	$(CAT) libsmp/smp9x.def >> mesasmp.def
	$(FASM) mesa_hook.asm $@

libsmp.dll: $(LIBSMP_OBJS)
	$(GCC_CC) $(CFLAGS) $(LIBSMP_OBJS) -shared -o $@ -Wl,--subsystem,windows -Wl,--kill-at -Wl,--enable-stdcall-fixup -lkernel32 -luser32 -lmsvcrt libsmp.def -static

mesasmp.dll: $(MESASMP_OBJS)
	$(GCC_CC) $(CFLAGS) $(MESASMP_OBJS) -shared -o $@ -Wl,--subsystem,windows -Wl,--kill-at -Wl,--enable-stdcall-fixup -lkernel32 -luser32 -lmsvcrt mesasmp.def -static

tests/smpload.exe: tests/smpload.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS_WIN)

tests/prime1.exe: tests/prime1.gcc.o fixlink.exe
	$(GCC_CC) $(GCC_CFLAGS) tests/prime1.gcc.o -o $@ $(GCC_LDFLAGS)
	fixlink -relink $@ libsmp.dll kernel32.dll msvcrt.dll

tests/prime2.exe: $(SMP9X_OBJS) tests/prime2.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS)
	
tests/prime3.exe: $(SMP9X_OBJS) tests/prime3.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS)

tests/systemcall.exe: $(SMP9X_OBJS) tests/systemcall.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS_WIN)

tests/doscall.exe: $(SMP9X_OBJS) tests/doscall.gcc.o
	$(GCC_CC) $(GCC_CFLAGS) $^ -o $@ $(GCC_LDFLAGS)

%.lnk: GNUMakefile
	echo system win_vxd dynamic > $@
	echo option map=$*.map >> $@
	echo option nodefaultlibs >> $@
	echo name $(BIN) >> $@
	$(foreach obj,$(SMP_VXD_OBJS),echo file $(obj) >> $@ &&) true
	echo segment '_TEXT'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment '_DATA'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment 'CONST'  PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment 'CONST2' PRELOAD NONDISCARDABLE IOPL >> $@
	echo segment '_BSS'   PRELOAD NONDISCARDABLE IOPL >> $@
	echo export VXD_DDB.1 >> $@

$(BIN): $(TOOLS) $(SMP_VXD_OBJS) smp.lnk
	wlink op quiet @smp.lnk
	fixlink.exe -vxd32 $@

clean:
	-$(RM) smp.lnk
	-$(RM) *.err
	-$(RM) $(SMP_VXD_OBJS)
	-$(RM) $(BIN)
	-$(RM) $(SMP9X_OBJS)
	-$(RM) $(SMP_TESTS)
	-$(RM) $(SMP_TESTS_OBJS)
	-$(RM) $(LIBSMP_OBJS)
	-$(RM) libsmp.dll
	-$(RM) $(MESASMP_OBJS)
	-$(RM) mesasmp.dll
	-$(RM) $(GENERATED)
	-$(RM) $(TOOLS)

release: all
	$(CP) smp.vxd release/driver/smp.vxd
	$(CP) libsmp.dll release/test-basic/libsmp.dll
	$(CP) mesasmp.dll release/test-mesa3d/mesasmp.dll
	$(CP) tests/*.exe release/test-basic/
	$(CP) README.md release/readme.txt
	$(CP) LICENSE release/licence.txt
